export default {
  // place to separate constant
  START_FETCH: 'START_FETCH',
  FINISH_FETCH: 'FINISH_FETCH',
  HANDLE_FETCH_ERROR: 'HANDLE_FETCH_ERROR',

  GET_PATIENTS: 'GET_PATIENTS',
  ADD_PATIENT: 'ADD_PATIENT',
  EDIT_PATIENT_PROFILE: 'EDIT_PATIENT_PROFILE',
  REMOVE_PATIENT: 'REMOVE_PATIENT',
};
