export default {
  ADD_ITEM: 'ADD_ITEM',
  SET_ITEMS_LIST: 'SET_ITEMS_LIST',
  EDIT_ITEM: 'EDIT_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',

  SET_FETCH_STATUS: 'SET_FETCH_STATUS',
  SET_ERROR_STATE: 'SET_ERROR_STATE',
};
