export default {
  START_FETCH: 'START_FETCH',
  FINISH_FETCH: 'FINISH_FETCH',
  HANDLE_ERROR: 'HANDLE_ERROR',

  GET_RECORDS: 'GET_RECORDS',
  ADD_RECORD: 'ADD_RECORD',
  EDIT_RECORD: 'EDIT_RECORD',
  REMOVE_RECORD: 'REMOVE_RECORD',
};
